---
# tasks file for agent
- name: ensure customized data directory
  become: yes
  file:
    path: "{{ datadir_contents }}"
    state: directory
    mode: 0755

- name: RancherOS rancher/agent
  docker_container:
    name: rancheragent
    image: rancher/agent
    privileged: yes
    state: started
    restart_policy: always
    volumes:
    - "/var/run/docker.sock:/var/run/docker.sock"
    - "{{ datadir_contents }}:/var/lib/rancher"
    command: "{{ url_contents }}"
    env:
      CATTLE_AGENT_IP: "{{ ip_contents }}"
      CATTLE_HOST_LABELS: "{{ labels_contents }}"
